language: node_js
node_js:
  - '10'

sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=3

before_install:
  - docker --version

script:
  - npm run test:ci

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
