language: node_js
node_js:
  - '10'

sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=2

before_install:
  - docker --version
  - docker-compose --version

# Skip default npm install for Docker workflow
install: true

script: docker-compose -f docker-compose.test.yml up --exit-code-from cypress

deploy:
  provider: script
  # Prevent Travis from resetting working directory after build
  skip_cleanup: true
  script: npx semantic-release
  on:
    branch: master
