language: node_js
node_js:
  - '10'

env:
  - DOCKER_COMPOSE_VERSION=2

# safelist
branches:
  only:
    - master

before_install:
  - docker --version
  - docker-compose --version
  # Setup Code Climate test reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# Skip default npm install for Docker workflow
install: true

script:
  # Building the app image will install dependencies then lint and unit test so
  # that image is ready to build app bundle when run
  - docker build -t crystal-ball/webpack-base .
  # Copy code coverage report into Travis workspace for Code Climate test
  # coverage reporting
  - docker run --rm -v $(pwd)/coverage:/tmp crystal-ball/webpack-base cp -a /usr/src/react-application-prototype/coverage/. /tmp/
  # Run the acceptance tests 🎉
  - docker-compose -f docker-compose.test.yml up --exit-code-from cypress

# Call Code Climate reporter with results, note the --prefix option is used to
# strip the file paths output from the Docker container
after_script:
  - ./cc-test-reporter after-build --prefix /usr/src --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: script
  # Prevent Travis from resetting working directory after build
  skip_cleanup: true
  # Running semantic release requires installing node deps to workspace,
  # explicitly set CI env var for future proofing skipping Cypress install in
  # post-install script
  script: CI=true npm install && npx semantic-release
  on:
    branch: master

# ☎️ Slack
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: ac/4ZwzBG5WFTK7iJd+cO+Qk+IHNZH02bWVm0DOyVXRYQl8tHvQLM7/Ov0mHeD5fDb9Pnk36xw2yAvuN6RdxpMUnWIKHqgE3eqddI2hFj16efSkBValJUXkQIp3dUyyajN2uYGz2VG0aOWxCiiY5uurigJdJ11BlVKbXZ9OhMzrxa/KVlRGWKUnrtCUquLqA97YGRpaG7xO63CJkYN+v0mfeFZR2yZ31bQATSavOGncu4sniL7uTChc12A3wWGC3QpV3Aq/QkJXKBMuOtZcUy7ikXA8jSqajST1p6M+PLzidHoQ7ifN6cyDPfOUsx6MnBhycYmEM0bO8StTLVX6rhL+Fe0GQydloIyauBAB/4/RM3qytxMeKn9se2JAIke7CbubdWXnqm4TMZskZxcHi0YRCiX0ZWTZx8rODLXThBsznfgiovuDurPBWvH982vp4NfjYK5OH987zkmFCzcP0IuvYEXQ+hLjiHrzY8LR7m3rJccuhDdoLGxHSxHLOLK3ZDPHmViX72oLuc+QCAJC0YTmAS16jK483Y0WhcsAGzpZVxc5TJ4oVnaxM8Xv/MQ/qm/st4cv7RfLhVEtt75Hev0HFZ0oJikeJVWgGVWwh70Kj4YnoWtt9ixVfVCf4oj+kWUBbpUAv51xuqXXsO65CLmsCVDfCQ2EAGNoam7fgXv0=
