version: '3'
services:
  test:
    build:
      context: .
      dockerfile: ./test-app/Dockerfile
    ports:
      - '5000:5000'
  cypress:
    build:
      context: .
      dockerfile: ./cypress/Dockerfile
    command: ./node_modules/.bin/cypress run --config baseUrl=http://test:5000
    depends_on:
      - test
    volumes:
      - ./cypress:/usr/cypress/cypress
      - ./cypress.json:/usr/cypress/cypress.json
