version: '3'
services:
  app:
    build: .
    ports:
      # Both the webpack serve and hot client ports must be exposed!
      - '3000:3000'
      - '3001:3001'
      - '5000:5000'
    volumes:
      # Mount resources that we want kept in sync with local as volumes for development
      # webpack source
      - './src:/usr/src/app/node_modules/@crystal-ball/webpack-base/src'
      # Template project
      - './test-app/src:/usr/src/app/src'
      - './test-app/webpack.config.js:/usr/src/app/webpack.config.js'
    entrypoint: /bin/sh
