version: '3'
services:
  webpack:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - './src:/usr/src/app/node_modules@inspirescript/webpack-configs/src'
      - './guides:/usr/src/app/guides'
      - './project-template/src:/usr/src/app/src'
      - './project-template/webpack.config.js:/usr/src/app/webpack.config.js'
    entrypoint: /bin/sh
