version: '3'
services:
  webpack:
    build: .
    ports:
      - '3000:3000'
    volumes:
      # Mount resources that we want kept in sync with local as volumes for development
      # webpack source
      - './src:/usr/src/app/node_modules/@inspirescript/webpack-configs/src'
      # Guides
      - './guides:/usr/src/app/guides'
      # Template project
      - './project-template/src:/usr/src/app/src'
      - './project-template/webpack.config.js:/usr/src/app/webpack.config.js'
    entrypoint: /bin/sh
