version: '2.4'

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
      - '5000:5000'
    volumes:
      # Mount source so we don't have to rebuild image on every file change
      - './src:/usr/src/app/node_modules/@crystal-ball/webpack-base/src'
    command: /bin/sh
