import merge from 'webpack-merge'

import validatePaths from './validate-paths'
import development from './development'
import production from './production'
import common from './common'

/**
 * Base Webpack configs are generated by:
 * 1. Generate paths using env w/ defaults+configured paths
 * 2. Generate configs common to all environments using `common`
 * 3. Generate env specific configs with `merge`
 *
 * `paths(env) => merge(common(paths) + (dev(paths) || prod(paths)))`
 */
export default function webpackConfigs({ env = 'development', paths = {} } = {}) {
  // Ensure that Babel has an env for .babelrc
  process.env.BABEL_ENV = process.env.BABEL_ENV || env

  // Resolve paths config for env and passed paths
  const validatedPaths = validatePaths({ env, paths })

  // Use webpack-merge and dev vs prod specific configs to return complete webpack
  // configuration object
  return env === 'production'
    ? merge(common(validatedPaths), production(validatedPaths))
    : merge(common(validatedPaths), development(validatedPaths))
}
