name: CI/CD
on: [push]

jobs:
  # --- Package testing ✅
  test:
    name: Continuous Integration
    if: contains(github.event.head_commit.message, 'skip ci') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.15'
      # Acceptance tests workflow manages:
      #  1. Setting Cypress+Percy git branch env vars (Github actions aren't supported yet)
      #  2. Building the application Docker image (executes linting and unit tests)
      #  3. Copy code coverage output from Docker image to workspace for uploading later
      #  4. Running Cypress tests using Docker Compose and NGINX
      # export PERCY_BRANCH="${PERCY_BRANCH:-${GITHUB_REF:11}}"
      # docker build -t crystal-ball/webpack-base .
      # docker run --rm -v $(pwd)/coverage:/tmp crystal-ball/webpack-base cp -a /usr/src/react-application-prototype/coverage/. /tmp/
      # docker-compose -f docker-compose.test.yml up --exit-code-from cypress
      - name: Test
        run: |
          CI=true CYPRESS_INSTALL_BINARY=0 npm install --no-optional --loglevel error
          npm run test:lint
          npm run test:unit
        env:
          PERCY_BRANCH: ${{ github.head_ref }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      # Upload test code coverage report to Code Climate (branch must be explicitly set)
      - name: Codecov
        uses: codecov/codecov-action@v2

  # --- Package publishing 🚀
  publish:
    name: Continuous Deployment
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.15'
      - name: Install
        run: CI=true CYPRESS_INSTALL_BINARY=0 npm install
      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_NPM_TOKEN }}
